### ISSUE TITLE
Could not find dataset_info.csv

### ISSUE THREAD

**Issue by MaahiKhazi** [IDT-ITI/XAI-Deepfakes#1]
The preprocessing step requires dataset_info.csv but i could not download it from the script given by Faceforensics++. Can anyone please clarify what to do.

**Comment by e-apostolidis** [comment]
Many thanks for your interest in our project. This file is related to the FaceForensics++ dataset and thus is among the files that can be downloaded from the GitHub repository of FaceForensics++. However, for easier access, I have added the "dataset_info.csv" file in the /data/csvs/ directory of our GitHub page, and updated the relevant part of the documentation.
